//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class StudyMoverSetting
{

    private StudyMoverSettings[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Settings", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public StudyMoverSettings[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class StudyMoverSettings
{

    private string calledAEField;

    private string storeCalledAEField;

    private string store_AE_NameField;

    private string storagePathField;

    private string hostField;

    private int portField;

    private string storeHostField;

    private int storePortField;

    private int localPortField;

    private string StoreHostRetreiveField;

    private int StorePortRetreiveField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CalledAE
    {
        get
        {
            return this.calledAEField;
        }
        set
        {
            this.calledAEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StoreCalledAE
    {
        get
        {
            return this.storeCalledAEField;
        }
        set
        {
            this.storeCalledAEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Store_AE_Name
    {
        get
        {
            return this.store_AE_NameField;
        }
        set
        {
            this.store_AE_NameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StoragePath
    {
        get
        {
            return this.storagePathField;
        }
        set
        {
            this.storagePathField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Host
    {
        get
        {
            return this.hostField;
        }
        set
        {
            this.hostField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Port
    {
        get
        {
            return this.portField;
        }
        set
        {
            this.portField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StoreHost
    {
        get
        {
            return this.storeHostField;
        }
        set
        {
            this.storeHostField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int StorePort
    {
        get
        {
            return this.storePortField;
        }
        set
        {
            this.storePortField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int LocalPort
    {
        get
        {
            return this.localPortField;
        }
        set
        {
            this.localPortField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StoreHostRetreive
    {
        get
        {
            return this.StoreHostRetreiveField;
        }
        set
        {
            this.StoreHostRetreiveField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int StorePortRetreive
    {
        get
        {
            return this.StorePortRetreiveField;
        }
        set
        {
            this.StorePortRetreiveField = value;
        }
    }
}
